In [751]:
from google.colab import drive
import os
import pandas as pd
from scipy import stats
import numpy as np

In [752]:

drive.mount('/content/drive')

DATA_DIR = '/content/drive/My Drive/data'

# 3. Automatically change the working directory so relative paths work
if os.path.exists(DATA_DIR):
    os.chdir(DATA_DIR)
    print(f"Successfully connected! Current working directory: {os.getcwd()}")
else:
    print(f"Error: The folder '{DATA_DIR}' could not be found.")
    print("Make sure to add a shortcut of the 'data' folder to your 'My Drive'.")

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
Successfully connected! Current working directory: /content/drive/.shortcut-targets-by-id/1_ib6SYLLQ6Asjybns0GSlgBDwFQrnmkj/data

### Uploading Data and Addressing Missing Values and Outliers

## Data Cleaning Methodology

The datasets are cleaned by addressing missing values and potential outliers.

### Missing values

Missing values are handled according to the meaning of the variable rather than
using one imputation method for every column.

The following rules are used:

- Sentinel values representing missing data are converted to `NaN`.
- Rows missing an essential measurement are removed when the observation cannot
  be used for the analysis.
- Short gaps in sequential environmental measurements may be filled using
  linear interpolation when nearby observations provide a reasonable estimate.
- Missing categorical metadata is represented as `"Unknown"` when appropriate.
- Measurement or metadata values that cannot be reliably inferred are left as
  `NaN`.
- Median imputation is used only when a numerical variable can reasonably be
  represented by a typical value and interpolation is not appropriate.

### Outliers

The Interquartile Range (IQR) method is used consistently for outlier screening.

For each measurement:

- IQR = Q3 - Q1
- Lower bound = Q1 - 1.5 × IQR
- Upper bound = Q3 + 1.5 × IQR

Values outside these bounds are considered statistical outliers. However,
statistical outliers are not automatically removed. They are investigated using
their units, sampling context, location, quality information, and physical
plausibility.

Values are removed only when there is evidence that they are clearly erroneous
or physically implausible.

In [753]:
# Load all datasets
bradentonFL = pd.read_csv("bradentonFL_tempData.csv")
floridaCyanotoxins = pd.read_csv("florida_cyanotoxins_2015-01-01_to_2026-06-17.csv")
habsos = pd.read_csv("habsos_cellcounts.csv")
motemarine = pd.read_csv("MoteMarine_BottomTemp.csv")
nutrientsFL = pd.read_csv("NutrientsFL_2006_2025.csv")
sarasota = pd.read_csv("Sarasota_Wind&Temp.csv")

/tmp/ipykernel_1220/3135485723.py:3: DtypeWarning: Columns (48) have mixed types. Specify dtype option on import or set low_memory=False.
  floridaCyanotoxins = pd.read_csv("florida_cyanotoxins_2015-01-01_to_2026-06-17.csv")
/tmp/ipykernel_1220/3135485723.py:4: DtypeWarning: Columns (23) have mixed types. Specify dtype option on import or set low_memory=False.
  habsos = pd.read_csv("habsos_cellcounts.csv")
/tmp/ipykernel_1220/3135485723.py:7: DtypeWarning: Columns (1,2,4,6,8,10,12,14) have mixed types. Specify dtype option on import or set low_memory=False.
  sarasota = pd.read_csv("Sarasota_Wind&Temp.csv")

## bradentonFL_tempData.csv

In [754]:
print("Shape:", bradentonFL.shape)

Shape: (4018, 8)

In [755]:
bradentonFL.head()

,COOPID,YEAR,MONTH,DAY,PRECIPITATION,MAX TEMP,MIN TEMP,MEAN TEMP
0,80945,2015,1,1,0.0,74.0,60.0,
1,80945,2015,1,2,0.0,78.0,64.0,
2,80945,2015,1,3,0.0,85.0,70.0,
3,80945,2015,1,4,0.0,83.0,69.0,
4,80945,2015,1,5,0.0,75.0,61.0,

In [756]:
# Check missing values before cleaning.
print("Missing values:")
print(bradentonFL.isna().sum())

Missing values:
COOPID            0
 YEAR             0
 MONTH            0
 DAY              0
 PRECIPITATION    0
 MAX TEMP         0
 MIN TEMP         0
 MEAN TEMP        0
dtype: int64

In [757]:
print("\nColumn names:")
print(bradentonFL.columns)

Column names:
Index(['COOPID', ' YEAR', ' MONTH', ' DAY', ' PRECIPITATION', ' MAX TEMP',
       ' MIN TEMP', ' MEAN TEMP'],
      dtype='object')

In [758]:
# Rename columns for easier reference
bradentonFL.rename(
    columns={
        'COOPID': "coop_id",
        ' YEAR': 'year',
        ' MONTH': 'month',
        ' DAY': 'day',
        ' PRECIPITATION': 'precipitation',
        ' MAX TEMP': 'max_temp',
        ' MIN TEMP': 'min_temp',
        ' MEAN TEMP': 'mean_temp'
    },
    inplace=True
)

In [759]:
# Remove mean temperature because it will not needed for the analysis
bradentonFL.drop(columns='mean_temp', inplace=True)

In [760]:
bradentonFL.describe()

,coop_id,year,month,day,precipitation,max_temp,min_temp
count,4018.0,4018.00000,4018.000000,4018.000000,4018.000000,4018.000000,4018.000000
mean,80945.0,2020.00000,6.522648,15.730463,0.028726,84.121379,66.079841
std,0.0,3.16275,3.449210,8.801536,3.565303,11.761406,12.512208
min,80945.0,2015.00000,1.000000,1.000000,-99.990000,-99.900000,-99.900000
25%,80945.0,2017.00000,4.000000,8.000000,0.000000,80.000000,60.000000
50%,80945.0,2020.00000,7.000000,16.000000,0.000000,86.000000,69.000000
75%,80945.0,2023.00000,10.000000,23.000000,0.040000,91.000000,75.000000
max,80945.0,2025.00000,12.000000,31.000000,11.650000,101.000000,83.000000

### Bradenton Missing Values

The precipitation and temperature columns contain sentinel values such as
`-99.99` and `-99.9`. These values represent missing observations rather than
actual environmental measurements, so they are converted to `NaN`.

Missing weather measurements are not median-imputed because doing so would
create artificial weather observations for days when measurements were not
recorded.

In [761]:
# Check for sentinel values representing missing temperature or precipitation data
bradentonFL[
    ["precipitation", "max_temp", "min_temp"]
].isin([-99.99, -99.9]).sum()

precipitation    5
max_temp         7
min_temp         8
dtype: int64

In [762]:
# Replace sentinel values with NaN so they are treated as missing values
bradentonFL["precipitation"] = bradentonFL["precipitation"].replace([-99.99, -99.9], np.nan)
bradentonFL["max_temp"] = bradentonFL["max_temp"].replace(-99.9, np.nan)
bradentonFL["min_temp"] = bradentonFL["min_temp"].replace(-99.9, np.nan)

In [763]:
# Check for any remaining negative precipitation values
print(
    bradentonFL[
        ["precipitation", "max_temp", "min_temp"]
    ].isin([-99.99, -99.9]).sum()
)

print("\nRemaining missing values:")
print(bradentonFL.isna().sum())

precipitation    0
max_temp         0
min_temp         0
dtype: int64

Remaining missing values:
coop_id          0
year             0
month            0
day              0
precipitation    5
max_temp         7
min_temp         8
dtype: int64

In [765]:
# Check for any remaining negative precipitation values.
bradentonFL[
    bradentonFL["precipitation"] < 0
][
    ["year", "month", "day", "precipitation"]
]

Empty DataFrame
Columns: [year, month, day, precipitation]
Index: []

In [767]:
# Check whether minimum temperature exceeds maximum temperature.
print(
    "Rows where min_temp > max_temp:",
    (bradentonFL["min_temp"] > bradentonFL["max_temp"]).sum()
)

Rows where min_temp > max_temp: 0

### Bradenton Outlier Detection

IQR is applied to precipitation, maximum temperature, and minimum temperature.
The date variables and station identifier are not treated as environmental
measurement outliers.

IQR outliers are investigated rather than automatically deleted because extreme
weather conditions can be legitimate observations.

In [768]:
# Variables used for IQR outlier screening.
measurement_cols = [
    "precipitation",
    "max_temp",
    "min_temp"
]

# Calculate Q1, Q3, and IQR.
Q1 = bradentonFL[measurement_cols].quantile(0.25)
Q3 = bradentonFL[measurement_cols].quantile(0.75)

IQR = Q3 - Q1

lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

print("Lower bounds:")
print(lower_bound)

print("\nUpper bounds:")
print(upper_bound)

# Identify IQR outliers.
outliers = (
    (bradentonFL[measurement_cols] < lower_bound) |
    (bradentonFL[measurement_cols] > upper_bound)
)

print("\nNumber of IQR outliers:")
print(outliers.sum())

Lower bounds:
precipitation    -0.06
max_temp         63.50
min_temp         37.50
dtype: float64

Upper bounds:
precipitation      0.1
max_temp         107.5
min_temp          97.5
dtype: float64

Number of IQR outliers:
precipitation    810
max_temp         117
min_temp          17
dtype: int64

In [769]:
# Inspect precipitation outliers.
display(
    bradentonFL[outliers["precipitation"]][
        ["year", "month", "day", "precipitation"]
    ].sort_values(
        "precipitation",
        ascending=False
    ).head(20)
)

# Inspect maximum-temperature outliers.
display(
    bradentonFL[outliers["max_temp"]][
        ["year", "month", "day", "max_temp"]
    ].sort_values(
        "max_temp",
        ascending=False
    ).head(20)
)

# Inspect minimum-temperature outliers.
display(
    bradentonFL[outliers["min_temp"]][
        ["year", "month", "day", "min_temp"]
    ].sort_values(
        "min_temp"
    ).head(20)
)

      year  month  day  precipitation
968   2017      8   26          11.65
2827  2022      9   28           7.09
3503  2024      8    4           7.00
489   2016      5    4           6.74
608   2016      8   31           6.71
3504  2024      8    5           6.30
1980  2020      6    3           6.03
2141  2020     11   11           5.80
3569  2024     10    9           4.62
1449  2018     12   20           4.30
2371  2021      6   29           4.20
3065  2023      5   24           4.00
942   2017      7   31           3.83
1940  2020      4   24           3.65
2792  2022      8   24           3.50
3028  2023      4   17           3.28
3531  2024      9    1           3.22
983   2017      9   10           2.90
2079  2020      9   10           2.85
522   2016      6    6           2.83

      year  month  day  max_temp
40    2015      2   10      63.0
367   2016      1    3      63.0
708   2016     12    9      63.0
420   2016      2   25      63.0
421   2016      2   26      63.0
1110  2018      1   15      63.0
1102  2018      1    7      63.0
1176  2018      3   22      63.0
1125  2018      1   30      63.0
1096  2018      1    1      63.0
1446  2018     12   17      63.0
2161  2020     12    1      63.0
3668  2025      1   16      63.0
3297  2024      1   11      63.0
3303  2024      1   17      63.0
2948  2023      1   27      63.0
3984  2025     11   28      63.0
2162  2020     12    2      63.0
1883  2020      2   27      63.0
1525  2019      3    6      63.0

      year  month  day  min_temp
1113  2018      1   18      29.0
50    2015      2   20      34.0
2915  2022     12   25      34.0
1075  2017     12   11      34.0
2914  2022     12   24      35.0
2587  2022      1   31      35.0
1074  2017     12   10      35.0
389   2016      1   25      36.0
1100  2018      1    5      36.0
1099  2018      1    4      36.0
738   2017      1    8      36.0
739   2017      1    9      36.0
2586  2022      1   30      36.0
1847  2020      1   22      37.0
1108  2018      1   13      37.0
1114  2018      1   19      37.0
3677  2025      1   25      37.0

## florida_cyanotoxins_2015-01-01_to_2026-06-17.csv

In [770]:
print("Shape:", floridaCyanotoxins.shape)

Shape: (98884, 65)

In [771]:
floridaCyanotoxins.head()

,Org_Identifier,Org_FormalName,Project_Identifier,Location_Identifier,Location_Name,Location_Type,Location_State,Location_HUCEightDigitCode,Location_HUCTwelveDigitCode,Location_TribalLand,Location_Latitude,Location_Longitude,Activity_ActivityIdentifier,Activity_TypeCode,Activity_Media,Activity_MediaSubdivision,ActivityBiological_AssemblageSa,Activity_StartDate,Activity_StartTime,Activity_StartTimeZone,Activity_DepthHeightMeasure,Activity_DepthHeightMeasureUnit,SampleCollectionMethod_Name,Result_ResultDetectionCondition,Result_Characteristic,Result_CharacteristicUserSuppli,Result_MethodSpeciation,Result_SampleFraction,ResultBiological_Intent,ResultBiological_Taxon,ResultDepthHeight_Measure,ResultDepthHeight_MeasureUnit,Result_MeasureIdentifier,Reslt_Measre,Result_MeasureUnit,Result_MeasureQualifierCode,Result_MeasureStatusIdentifier,Result_StatisticalBase,Result_MeasureValueType,DataQuality_ResultComment,DetectionLimit_TypeA,DetectionLimit_MeasureA,DetectionLimit_MeasureUnitA,DetectionLimit_CommentA,DetectionLimit_TypeB,DetectionLimit_MeasureB,DetectionLimit_MeasureUnitB,DetectionLimit_CommentB,ResultAnalyticalMethod_Identifi,ResultAnalyticalMethod_Identi_1,ResultAnalyticalMethod_Name,LabInfo_AnalysisStartDate,LabInfo_AnalysisStartTime,LabInfo_AnalysisStartTimeZone,ResultAnalyticalMethod_Url,Result_DetectionLimitProfileDow,Result_LabSamplePrepProfileDown,ProviderName,Result_CharacteristicComparable,Result_CharacteristicGroup,Org_Type,LastChangeDate,USGSpcode,ObjectId,Value_control
0,NARS_WQX,EPA National Aquatic Resources Survey (NARS),"[""NARS_NCCA2015""]",NARS_WQX-NCA_FL-10246,NCA_FL-10246,Ocean,Florida,NaN,NaN,NaN,27.887829,-82.557660,NARS_WQX-NCA_FL-10246:06012015:SR:AT,Sample-Routine,Water,NaN,NaN,1.433130e+12,NaN,NaN,NaN,NaN,NCCA Grab Sample,NaN,Microcystin,NaN,NaN,NaN,NaN,NaN,NaN,NaN,STORET-937617381,NaN,ug/L,NaN,Final,NaN,Actual,NaN,Minimum Reporting Level,0.263,ug/L,NaN,NaN,NaN,NaN,NaN,520011,ABRAXIS LLC,"Microcystins and Nodularins by Immunoassay, Mi...",NaN,NaN,NaN,NaN,https://www.waterqualitydata.us/data/providers...,NaN,STORET,NaN,"Cyanotoxins, Phytotoxins",Federal/US Government,Fri Jan 31 08:59:46 GMT 2025,NaN,23431,A
1,NARS_WQX,EPA National Aquatic Resources Survey (NARS),"[""NARS_NCCA2015""]",NARS_WQX-NCA_FL-10245,NCA_FL-10245,Ocean,Florida,NaN,NaN,NaN,27.906991,-82.480553,NARS_WQX-NCA_FL-10245:06022015:SR:AT,Sample-Routine,Water,NaN,NaN,1.433220e+12,NaN,NaN,NaN,NaN,NCCA Grab Sample,NaN,Microcystin,NaN,NaN,NaN,NaN,NaN,NaN,NaN,STORET-937617442,NaN,ug/L,NaN,Final,NaN,Actual,NaN,Minimum Reporting Level,0.263,ug/L,NaN,NaN,NaN,NaN,NaN,520011,ABRAXIS LLC,"Microcystins and Nodularins by Immunoassay, Mi...",NaN,NaN,NaN,NaN,https://www.waterqualitydata.us/data/providers...,NaN,STORET,NaN,"Cyanotoxins, Phytotoxins",Federal/US Government,Fri Jan 31 08:59:46 GMT 2025,NaN,22625,A
2,NARS_WQX,EPA National Aquatic Resources Survey (NARS),"[""NARS_NCCA2015""]",NARS_WQX-NCA_FL-10297,NCA_FL-10297,Ocean,Florida,NaN,NaN,NaN,27.936200,-82.426381,NARS_WQX-NCA_FL-10297:06022015:SR:AT,Sample-Routine,Water,NaN,NaN,1.433220e+12,NaN,NaN,NaN,NaN,NCCA Grab Sample,NaN,Microcystin,NaN,NaN,NaN,NaN,NaN,NaN,NaN,STORET-937617450,NaN,ug/L,NaN,Final,NaN,Actual,NaN,Minimum Reporting Level,0.263,ug/L,NaN,NaN,NaN,NaN,NaN,520011,ABRAXIS LLC,"Microcystins and Nodularins by Immunoassay, Mi...",NaN,NaN,NaN,NaN,https://www.waterqualitydata.us/data/providers...,NaN,STORET,NaN,"Cyanotoxins, Phytotoxins",Federal/US Government,Fri Jan 31 08:59:46 GMT 2025,NaN,22713,A
3,NARS_WQX,EPA National Aquatic Resources Survey (NARS),"[""NARS_NCCA2015""]",NARS_WQX-NCA_FL-10299,NCA_FL-10299,Ocean,Florida,NaN,NaN,NaN,27.646342,-82.703638,NARS_WQX-NCA_FL-10299:06032015:SR:AT,Sample-Routine,Water,NaN,NaN,1.433300e+12,NaN,NaN,NaN,NaN,NCCA Grab Sample,NaN,Microcystin,NaN,NaN,NaN,NaN,NaN,NaN,NaN,STORET-937617465,NaN,ug/L,NaN,Final,NaN,Actual,NaN,Minimum Reporting Level,0.263,ug/L,NaN,NaN,NaN,NaN,NaN,520011,ABRAXIS LLC,"Microcystins and Nodularins by Immunoassay, Mi...",NaN,NaN,NaN,NaN,https://www.waterqualitydata.us/data/providers...,NaN,STORET,NaN,"Cyanotoxins, Phytotoxins",Federal/US Government,Fri Jan 31 08:59:46 GMT 2025,NaN,25340,A
4,NARS_WQX,EPA National Aquatic Resources Survey (NARS),"[""NARS_NCCA2015""]",NARS_WQX-NCA_FL-10248,NCA_FL-10248,Ocean,Florida,NaN,NaN,NaN,27.599149,-82.664045,NARS_WQX-NCA_FL-10248:06032015:SR:AT,Sample-Routine,Water,NaN,NaN,1.433300e+12,NaN,NaN,NaN,NaN,NCCA Grab Sample,NaN,Microcystin,NaN,NaN,NaN,NaN,NaN,NaN,NaN,STORET-937617472,NaN,ug/L,NaN,Final,NaN,Actual,NaN,Minimum Reporting Level,0.263,ug/L,NaN,NaN,NaN,NaN,NaN,520011,ABRAXIS LLC,"Microcystins and Nodularins by Immunoassay, Mi...",NaN,NaN,NaN,NaN,https://www.waterqualitydata.us/data/providers...,NaN,STORET,NaN,"Cyanotoxins, Phytotoxins",Federal/US Government,Fri Jan 31 08:59:46 GMT 2025,NaN,25355,A

In [772]:
# Check missing values.
print(
    floridaCyanotoxins.isna().sum()[
        floridaCyanotoxins.isna().sum() > 0
    ]
)

Location_HUCEightDigitCode           188
Location_HUCTwelveDigitCode          308
Location_TribalLand                98884
Activity_MediaSubdivision            236
ActivityBiological_AssemblageSa    98884
Activity_StartTime                   220
Activity_StartTimeZone               220
Activity_DepthHeightMeasure          228
Activity_DepthHeightMeasureUnit      228
Result_ResultDetectionCondition    98884
Result_CharacteristicUserSuppli    98884
Result_MethodSpeciation            98884
Result_SampleFraction                220
ResultBiological_Intent            98884
ResultBiological_Taxon             98884
ResultDepthHeight_Measure          98884
ResultDepthHeight_MeasureUnit      98884
Reslt_Measre                         131
Result_MeasureUnit                    60
Result_MeasureQualifierCode        98884
Result_StatisticalBase             98884
DataQuality_ResultComment           1772
DetectionLimit_TypeA                  60
DetectionLimit_MeasureA               60
DetectionLimit_MeasureUnitA           60
DetectionLimit_CommentA            98884
DetectionLimit_TypeB               98884
DetectionLimit_MeasureB            98884
DetectionLimit_MeasureUnitB        98884
DetectionLimit_CommentB            98884
LabInfo_AnalysisStartDate            140
LabInfo_AnalysisStartTime            220
LabInfo_AnalysisStartTimeZone        220
ResultAnalyticalMethod_Url         98884
Result_DetectionLimitProfileDow       60
Result_LabSamplePrepProfileDown    98884
Result_CharacteristicComparable    98884
USGSpcode                          98884
dtype: int64

In [773]:
# Remove columns that contain no data.
floridaCyanotoxins = floridaCyanotoxins.dropna(
    axis=1,
    how="all"
)

print("Shape after removing empty columns:", floridaCyanotoxins.shape)

Shape after removing empty columns: (98884, 45)

### Cyanotoxin Missing Values

`Reslt_Measre` is the primary measurement used for the analysis. Rows without
this measurement cannot contribute to the cyanotoxin analysis and are therefore
removed.

Other numerical fields, such as depth or geographic coordinates, are not
automatically median-imputed because replacing them with a typical value could
create artificial sampling information.

Categorical fields with missing values are represented as `"Unknown"`.

In [774]:
# Remove rows where the primary cyanotoxin measurement is missing.
floridaCyanotoxins = floridaCyanotoxins.dropna(
    subset=["Reslt_Measre"]
)

In [775]:
# Separate numerical and categorical columns for missing-value treatment
numerical_cols = floridaCyanotoxins.select_dtypes(include=["number"]).columns
categorical_cols = floridaCyanotoxins.select_dtypes(include=["object"]).columns

In [776]:
# Fill missing categorical values with "Unknown"
floridaCyanotoxins[categorical_cols] = floridaCyanotoxins[
    categorical_cols
].fillna("Unknown")

In [777]:
print("Remaining missing values:")
print(
    floridaCyanotoxins.isna().sum()[
        floridaCyanotoxins.isna().sum() > 0
    ]
)

Remaining missing values:
Location_HUCEightDigitCode      93
Location_HUCTwelveDigitCode    177
Activity_DepthHeightMeasure     97
DetectionLimit_MeasureA         60
dtype: int64

### Cyanotoxin Outlier Detection

IQR is applied to `Reslt_Measre`, the primary cyanotoxin measurement.

Because cyanotoxin concentrations can be strongly right-skewed, unusually high
measurements are expected to occur. Therefore, IQR outliers are investigated
before any decision to remove them.

In [778]:
# Examine the original distribution before removing any outliers.
floridaCyanotoxins["Reslt_Measre"].describe()

count    98753.000000
mean         0.449555
std          7.271026
min          0.060000
25%          0.100000
50%          0.250000
75%          0.250000
max        780.000000
Name: Reslt_Measre, dtype: float64

In [779]:
# Calculate IQR bounds.
Q1 = floridaCyanotoxins["Reslt_Measre"].quantile(0.25)
Q3 = floridaCyanotoxins["Reslt_Measre"].quantile(0.75)

IQR = Q3 - Q1

lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

print(f"Q1: {Q1:.3f}")
print(f"Q3: {Q3:.3f}")
print(f"IQR: {IQR:.3f}")
print(f"Lower bound: {lower_bound:.3f}")
print(f"Upper bound: {upper_bound:.3f}")

Q1: 0.100
Q3: 0.250
IQR: 0.150
Lower bound: -0.125
Upper bound: 0.475

In [780]:
# Identify IQR outliers.
measurement_outliers = floridaCyanotoxins[
    (floridaCyanotoxins["Reslt_Measre"] < lower_bound) |
    (floridaCyanotoxins["Reslt_Measre"] > upper_bound)
]

print("Number of IQR outliers:", len(measurement_outliers))

display(
    measurement_outliers[
        [
            "Result_Characteristic",
            "Reslt_Measre",
            "Result_MeasureUnit"
        ]
    ].sort_values(
        "Reslt_Measre",
        ascending=False
    ).head(30)
)

Number of IQR outliers: 15624

      Result_Characteristic  Reslt_Measre Result_MeasureUnit
19925        Microcystin LR         780.0               ug/L
11013        Microcystin LR         760.0               ug/L
76064        Microcystin LR         760.0               ug/L
56531        Microcystin LR         750.0               ug/L
362          Microcystin LR         730.0               ug/L
17648        Microcystin LR         600.0               ug/L
17671        Microcystin LR         600.0               ug/L
2367         Microcystin LR         490.0               ug/L
1049         Microcystin LR         450.0               ug/L
34048        Microcystin LR         410.0               ug/L
20639        Microcystin LR         390.0               ug/L
1004         Microcystin LR         300.0               ug/L
11314        Microcystin LR         280.0               ug/L
7317         Microcystin LR         230.0               ug/L
7300         Microcystin RR         220.0               ug/L
70729        Microcystin LR         200.0               ug/L
2644         Microcystin LR         200.0               ug/L
5799         Microcystin LR         190.0               ug/L
72858        Microcystin LR         160.0               ug/L
1211         Microcystin LR         160.0               ug/L
74589        Microcystin LR         150.0               ug/L
1210         Microcystin LR         150.0               ug/L
7276         Microcystin LR         140.0               ug/L
91846        Microcystin LR         130.0               ug/L
24043        Microcystin LR         120.0               ug/L
37484        Microcystin LA         120.0               ug/L
19791        Microcystin LR         110.0               ug/L
1980         Microcystin LR         110.0               ug/L
3288         Microcystin LR         110.0               ug/L
45586        Microcystin LR         100.0               ug/L

In [781]:
# Examine the largest measurements and their context.
display(
    floridaCyanotoxins.loc[
        floridaCyanotoxins["Reslt_Measre"] > 100,
        [
            "Location_Name",
            "Location_State",
            "Result_Characteristic",
            "Reslt_Measre",
            "Result_MeasureUnit",
            "Result_MeasureStatusIdentifier",
            "Result_MeasureValueType"
        ]
    ].sort_values(
        "Reslt_Measre",
        ascending=False
    )
)

,Location_Name,Location_State,Result_Characteristic,Reslt_Measre,Result_MeasureUnit,Result_MeasureStatusIdentifier,Result_MeasureValueType
19925,Lake Okeechobee - Pahokee Marina,Florida,Microcystin LR,780.0,ug/L,Final,Actual
11013,L004,Florida,Microcystin LR,760.0,ug/L,Final,Actual
76064,C44 Canal - Timer Powers Park Boat Ramp,Florida,Microcystin LR,760.0,ug/L,Final,Actual
56531,Moody Lake - SE,Florida,Microcystin LR,750.0,ug/L,Final,Actual
362,S352,Florida,Microcystin LR,730.0,ug/L,Final,Actual
17648,Harbor Isles - Southern Lobe,Florida,Microcystin LR,600.0,ug/L,Final,Actual
17671,Harbor Isles - Southern Lobe,Florida,Microcystin LR,600.0,ug/L,Final,Actual
2367,C44S80 St. Lucie Lock,Florida,Microcystin LR,490.0,ug/L,Final,Actual
1049,S79 Upstream of Lock,Florida,Microcystin LR,450.0,ug/L,Final,Actual
34048,Boat Ramp,Florida,Microcystin LR,410.0,ug/L,Final,Actual
20639,PALMOUT3,Florida,Microcystin LR,390.0,ug/L,Final,Actual
1004,ALVA BRIDGE,Florida,Microcystin LR,300.0,ug/L,Final,Actual
11314,LZ40,Florida,Microcystin LR,280.0,ug/L,Final,Actual
7317,Harbor Isles - Southern Lobe,Florida,Microcystin LR,230.0,ug/L,Final,Actual
7300,Harbor Isles - Southern Lobe,Florida,Microcystin RR,220.0,ug/L,Final,Actual
2644,Caloosahatchee st Jaycee Park,Florida,Microcystin LR,200.0,ug/L,Final,Actual
70729,Lake Okeechobee - S308C (lakeside),Florida,Microcystin LR,200.0,ug/L,Final,Actual
5799,Lake O SEast,Florida,Microcystin LR,190.0,ug/L,Final,Actual
1211,Prosperity Pointe Marina,Florida,Microcystin LR,160.0,ug/L,Final,Actual
72858,S308C,Florida,Microcystin LR,160.0,ug/L,Final,Actual
1210,C44S80 St. Lucie Lock,Florida,Microcystin LR,150.0,ug/L,Final,Actual
74589,Caloosahatchee - Jaycee Park,Florida,Microcystin LR,150.0,ug/L,Final,Actual
7276,Lake Jennie Jewel @ SE Corner,Florida,Microcystin LR,140.0,ug/L,Final,Actual
91846,Lake Okeechobee - S352,Florida,Microcystin LR,130.0,ug/L,Final,Actual
24043,Lake Okeechobee - S308C (lakeside),Florida,Microcystin LR,120.0,ug/L,Final,Actual
37484,Orange lake-McIntosh Bay,Florida,Microcystin LA,120.0,ug/L,Final,Actual
3288,HARBOR ISLE,Florida,Microcystin LR,110.0,ug/L,Final,Actual
1980,SE near Central Marine,Florida,Microcystin LR,110.0,ug/L,Final,Actual
19791,Lake Okeechobee- S308C,Florida,Microcystin LR,110.0,ug/L,Final,Actual

### Cyanotoxin Outlier Assessment

The IQR method identified unusually high cyanotoxin measurements. These values
were investigated using their characteristics, measurement units, locations,
and measurement status.

The extreme measurements were retained because they represent actual
measurements with consistent units and identifiable sampling locations. High
cyanotoxin concentrations may also contain important information about periods
of elevated algal bloom activity.

habsos_cellcounts.csv

In [782]:
print("Shape:", habsos.shape)

Shape: (219152, 26)

In [783]:
habsos.head()

,OBJECTID,DESCRIPTION,LATITUDE,LONGITUDE,STATE_ID,SAMPLE_DATE,SAMPLE_DEPTH,GENUS,SPECIES,CATEGORY,CELLCOUNT,CELLCOUNT_UNIT,CELLCOUNT_QA,SALINITY,SALINITY_UNIT,SALINITY_QA,WATER_TEMP,WATER_TEMP_UNIT,WATER_TEMP_QA,WIND_DIR,WIND_DIR_UNIT,WIND_DIR_QA,WIND_SPEED,WIND_SPEED_UNIT,WIND_SPEED_QA,QA_COMMENT
0,1,Tom Adams Bridge (Lemon Bay),26.93450,-82.3535,FL,1953-08-19 00:00:00,0.5,Karenia,brevis,medium,116000.0,cells/L,1,NaN,NaN,9,NaN,NaN,9,NaN,NaN,9,NaN,NaN,9,Missing/invalid time of day
1,2,Naples Pier,26.13163,-81.8063,FL,1953-08-26 00:00:00,0.5,Karenia,brevis,not observed,0.0,cells/L,1,NaN,NaN,9,NaN,NaN,9,NaN,NaN,9,NaN,NaN,9,Missing/invalid time of day
2,3,Piney Point; Lee County,26.53340,-81.9796,FL,1953-08-26 00:00:00,0.5,Karenia,brevis,not observed,0.0,cells/L,1,NaN,NaN,9,NaN,NaN,9,NaN,NaN,9,NaN,NaN,9,Missing/invalid time of day
3,4,Cortez Bridge,27.46840,-82.6937,FL,1953-08-26 00:00:00,0.5,Karenia,brevis,medium,178000.0,cells/L,1,NaN,NaN,9,NaN,NaN,9,NaN,NaN,9,NaN,NaN,9,Missing/invalid time of day
4,5,Sarasota Bay; 3 mi North of bridge,27.37750,-82.5708,FL,1953-09-03 00:00:00,0.5,Karenia,brevis,high,1732000.0,cells/L,1,NaN,NaN,9,NaN,NaN,9,NaN,NaN,9,NaN,NaN,9,Missing/invalid time of day

In [784]:
# Remove completely empty columns.
habsos = habsos.dropna(
    axis=1,
    how="all"
)

# WIND_SPEED and WIND_SPEED_UNIT do not contain usable information.
habsos = habsos.drop(
    columns=["WIND_SPEED", "WIND_SPEED_UNIT"]
)

print("Shape after column cleaning:", habsos.shape)

Shape after column cleaning: (219152, 22)

### HABSOS Missing Values

Water temperature and salinity are sequential environmental measurements.
Short gaps can therefore be estimated from surrounding observations using linear
interpolation.

A limit of two observations is used so that only short gaps are filled.

Categorical variables are filled with `"Unknown"`.

If both salinity and water temperature are missing for an observation, the
observation cannot contribute useful environmental measurements and is removed.

Sample depth is not a sequential measurement in this context, so missing depth
values are represented using the median depth rather than interpolation.

In [785]:
# Linearly interpolate only short gaps in environmental measurements.
habsos["WATER_TEMP"] = habsos[
    "WATER_TEMP"
].interpolate(
    method="linear",
    limit=2
)

habsos["SALINITY"] = habsos[
    "SALINITY"
].interpolate(
    method="linear",
    limit=2
)

In [786]:
# Fill missing categorical metadata with "Unknown".
categorical_cols = habsos.select_dtypes(
    include=["object"]
).columns

habsos[categorical_cols] = habsos[
    categorical_cols
].fillna("Unknown")

In [787]:
# Remove observations missing both major environmental measurements.
habsos = habsos.dropna(
    subset=["SALINITY", "WATER_TEMP"],
    how="all"
)

In [788]:
# Fill missing sample depth using the median.
habsos["SAMPLE_DEPTH"] = habsos[
    "SAMPLE_DEPTH"
].fillna(
    habsos["SAMPLE_DEPTH"].median()
)

In [789]:
print("Remaining missing values:")
print(
    habsos.isna().sum()[
        habsos.isna().sum() > 0
    ]
)

Remaining missing values:
SALINITY       9464
WATER_TEMP    11093
dtype: int64

### HABSOS Outlier Detection

IQR is applied separately to salinity, water temperature, and cell counts.

Cell counts are strongly right-skewed, so a log transformation is used before
IQR screening. The original `CELLCOUNT` values are retained.

In [790]:
# -----------------------------
# Salinity
# -----------------------------

Q1 = habsos["SALINITY"].quantile(0.25)
Q3 = habsos["SALINITY"].quantile(0.75)

IQR = Q3 - Q1

lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

print("Salinity")
print(f"Q1: {Q1:.3f}")
print(f"Q3: {Q3:.3f}")
print(f"IQR: {IQR:.3f}")
print(f"Lower bound: {lower_bound:.3f}")
print(f"Upper bound: {upper_bound:.3f}")

salinity_outliers = habsos[
    (habsos["SALINITY"] < lower_bound) |
    (habsos["SALINITY"] > upper_bound)
]

print("Number of IQR outliers:", len(salinity_outliers))

display(
    salinity_outliers[
        [
            "OBJECTID",
            "SALINITY",
            "SALINITY_UNIT",
            "SALINITY_QA",
            "QA_COMMENT"
        ]
    ].sort_values(
        "SALINITY",
        ascending=False
    ).head(20)
)

# Remove values above the selected physically plausible salinity range.
habsos = habsos.drop(
    habsos[
        habsos["SALINITY"] > 50
    ].index
)

print("Maximum salinity after cleaning:")
print(habsos["SALINITY"].max())

Salinity
Q1: 28.190
Q3: 35.000
IQR: 6.810
Lower bound: 17.975
Upper bound: 45.215
Number of IQR outliers: 7053

,OBJECTID,SALINITY,SALINITY_UNIT,SALINITY_QA,QA_COMMENT
204621,597495,308.00,ppt,4,Unknown
183985,406328,222.70,ppt,4,WDIR unexpected data in input;CATEGORIES from ...
204619,597493,161.00,Unknown,9,Unknown
204618,597492,87.50,Unknown,9,Unknown
196276,580077,72.00,ppt,4,WTEMP inferred as Fahrenheit based on value an...
196277,580078,64.80,Unknown,9,Unknown
182167,346512,57.80,ppt,4,SALINITY value (57.80) exceeds valid range (0....
196278,580079,57.60,Unknown,9,Unknown
4921,4922,57.00,ppt,4,SALINITY value (57.00) exceeds valid range (0....
5025,5026,56.00,ppt,4,SALINITY value (56.00) exceeds valid range (0....
4323,4324,55.61,ppt,4,SALINITY value (55.61) exceeds valid range (0....
4736,4737,55.60,ppt,4,SALINITY value (55.60) exceeds valid range (0....
4739,4740,54.40,ppt,4,SALINITY value (54.40) exceeds valid range (0....
177050,182150,54.32,ppt,4,CATEGORIES from provider;Converted from feet t...
5375,5376,53.70,ppt,4,SALINITY value (53.70) exceeds valid range (0....
5440,5441,53.00,ppt,4,WTEMP inferred as Fahrenheit based on value an...
5024,5025,53.00,Unknown,9,Unknown
196275,580076,52.90,ppt,4,WTEMP inferred as Fahrenheit based on value an...
110530,111131,52.30,ppt,4,SALINITY value (52.30) exceeds valid range (0....
5334,5335,52.00,ppt,4,SALINITY value (52.00) exceeds valid range (0....

Maximum salinity after cleaning:
50.0

In [791]:
# -----------------------------
# Water temperature
# -----------------------------

Q1 = habsos["WATER_TEMP"].quantile(0.25)
Q3 = habsos["WATER_TEMP"].quantile(0.75)

IQR = Q3 - Q1

lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

print("Water temperature")
print(f"Q1: {Q1:.3f}")
print(f"Q3: {Q3:.3f}")
print(f"IQR: {IQR:.3f}")
print(f"Lower bound: {lower_bound:.3f}")
print(f"Upper bound: {upper_bound:.3f}")

water_temp_outliers = habsos[
    (habsos["WATER_TEMP"] < lower_bound) |
    (habsos["WATER_TEMP"] > upper_bound)
]

print("Number of IQR outliers:", len(water_temp_outliers))

display(
    water_temp_outliers[
        [
            "OBJECTID",
            "WATER_TEMP",
            "WATER_TEMP_UNIT",
            "WATER_TEMP_QA",
            "QA_COMMENT"
        ]
    ].sort_values(
        "WATER_TEMP",
        ascending=False
    ).head(20)
)

Water temperature
Q1: 20.980
Q3: 29.000
IQR: 8.020
Lower bound: 8.950
Upper bound: 41.030
Number of IQR outliers: 921

,OBJECTID,WATER_TEMP,WATER_TEMP_UNIT,WATER_TEMP_QA,QA_COMMENT
184352,406695,1503.888889,deg. C,4,WTEMP value (1503.89) exceeds valid range (-2....
184302,406645,568.333333,deg. C,4,WTEMP value (568.33) exceeds valid range (-2.0...
213213,611134,149.111111,deg. C,4,Unknown
186448,434867,100.000000,deg. C,4,WTEMP value (100.00) exceeds valid range (-2.0...
212474,609991,8.940000,deg. C,1,Unknown
216736,616391,8.900000,deg. C,1,Unknown
217299,616954,8.900000,deg. C,1,Unknown
217300,616955,8.900000,deg. C,1,Unknown
93257,93613,8.900000,deg. C,1,Unknown
190310,547984,8.900000,deg. C,1,Unknown
151036,152747,8.900000,deg. C,1,Unknown
217297,616952,8.900000,deg. C,1,Unknown
119588,120373,8.900000,deg. C,1,Unknown
63388,63489,8.900000,deg. C,1,Unknown
176604,181704,8.888889,deg. C,1,CATEGORIES from provider;WTEMP inferred as Fah...
176605,181705,8.888889,deg. C,1,CATEGORIES from provider;WTEMP inferred as Fah...
93398,93755,8.866667,Unknown,9,Unknown
96804,97202,8.825000,Unknown,9,Unknown
217290,616945,8.800000,deg. C,1,Unknown
183954,406297,8.800000,deg. C,1,WDIR unexpected data in input;CATEGORIES from ...

In [792]:
# Remove water temperatures outside the selected physically plausible range.
habsos = habsos.drop(
    habsos[
        (habsos["WATER_TEMP"] > 40) |
        (habsos["WATER_TEMP"] < -2)
    ].index
)

print("Water temperature range after cleaning:")
print(habsos["WATER_TEMP"].describe())

Water temperature range after cleaning:
count    135843.000000
mean         24.519477
std           5.324568
min           0.000000
25%          20.980000
50%          25.200000
75%          29.000000
max          33.000000
Name: WATER_TEMP, dtype: float64

In [793]:
# -----------------------------
# Cell count
# -----------------------------

# Log-transform cell counts to reduce strong right-skew.
habsos["LOG_CELLCOUNT"] = np.log1p(
    habsos["CELLCOUNT"]
)

Q1 = habsos["LOG_CELLCOUNT"].quantile(0.25)
Q3 = habsos["LOG_CELLCOUNT"].quantile(0.75)

IQR = Q3 - Q1

lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

print("Log cell count")
print(f"Q1: {Q1:.3f}")
print(f"Q3: {Q3:.3f}")
print(f"IQR: {IQR:.3f}")
print(f"Lower bound: {lower_bound:.3f}")
print(f"Upper bound: {upper_bound:.3f}")

cellcount_outliers = habsos[
    (habsos["LOG_CELLCOUNT"] < lower_bound) |
    (habsos["LOG_CELLCOUNT"] > upper_bound)
]

print("Number of IQR outliers:", len(cellcount_outliers))

display(
    cellcount_outliers[
        [
            "OBJECTID",
            "CELLCOUNT",
            "LOG_CELLCOUNT",
            "CELLCOUNT_QA",
            "QA_COMMENT"
        ]
    ].sort_values(
        "CELLCOUNT",
        ascending=False
    ).head(30)
)

Log cell count
Q1: 0.000
Q3: 0.000
IQR: 0.000
Lower bound: 0.000
Upper bound: 0.000
Number of IQR outliers: 29450

,OBJECTID,CELLCOUNT,LOG_CELLCOUNT,CELLCOUNT_QA,QA_COMMENT
35164,35265,358000000.0,19.696044,1,Unknown
175953,181053,189456000.0,19.059667,1,CATEGORIES from provider;WTEMP inferred as Fah...
161844,164254,186266667.0,19.042690,1,Unknown
66166,66279,162188000.0,18.904267,1,Unknown
64846,64955,152210000.0,18.840772,1,Unknown
63895,63998,151100000.0,18.833452,1,Unknown
175941,181040,138000000.0,18.742764,1,CATEGORIES from provider;WTEMP inferred as Fah...
38088,38189,116016000.0,18.569239,1,Unknown
37947,38048,108672000.0,18.503845,1,Unknown
20859,20906,107000000.0,18.488339,1,Unknown
38100,38201,106563000.0,18.484247,1,Unknown
175716,180814,100000000.0,18.420681,1,CATEGORIES from provider;WTEMP unexpected data...
176058,181158,100000000.0,18.420681,1,CATEGORIES from provider;WTEMP unexpected data...
175952,181052,100000000.0,18.420681,1,CATEGORIES from provider;WTEMP inferred as Fah...
10088,10090,100000000.0,18.420681,1,Unknown
66087,66200,95625000.0,18.375945,1,Unknown
38089,38190,88750000.0,18.301334,1,Unknown
156460,158632,82800000.0,18.231939,1,Unknown
35611,35712,81700000.0,18.218565,1,Missing/invalid time of day
162162,164598,77295560.0,18.163147,1,Missing/invalid time of day
32776,32877,73000000.0,18.105970,1,Unknown
18745,18792,72540000.0,18.099649,1,Unknown
34909,35010,68500000.0,18.042344,1,Unknown
109916,110510,68420000.0,18.041176,1,Unknown
42421,42522,68333333.0,18.039908,1,Unknown
160472,162806,67254526.0,18.023995,1,Missing/invalid time of day
36729,36830,64843000.0,17.987480,1,Unknown
10089,10091,64000000.0,17.974394,1,Missing/invalid time of day
111994,112623,63506600.0,17.966654,1,Unknown
175968,181068,63000000.0,17.958645,1,CATEGORIES from provider;WTEMP inferred as Fah...

### HABSOS Outlier Assessment

Salinity values above 50 and water temperatures above 40°C or below -2°C were
removed because they fall outside the selected physically plausible ranges.

Other IQR outliers were retained when they could represent legitimate
environmental variation. In particular, high cell counts may represent periods
of increased algal abundance rather than erroneous measurements.

MoteMarine_BottomTemp.csv

In [794]:
print("Shape:", motemarine.shape)

Shape: (31730, 6)

In [795]:
motemarine.head()

,time,latitude,longitude,z,sea_water_temperature,sea_water_temperature_qc_agg
0,UTC,degrees_north,degrees_east,m,degree_Celsius,NaN
1,2020-08-13T15:00:00Z,27.3292,-82.5564,-2.0,30.929,1.0
2,2020-08-13T16:00:00Z,27.3292,-82.5564,-2.0,31.073,1.0
3,2020-08-13T17:00:00Z,27.3292,-82.5564,-2.0,31.217,1.0
4,2020-08-13T18:00:00Z,27.3292,-82.5564,-2.0,31.274,1.0

In [796]:
# Check missing values.
print(
    motemarine.isna().sum()[
        motemarine.isna().sum() > 0
    ]
)

sea_water_temperature_qc_agg    1
dtype: int64

In [797]:
# Convert environmental measurements to numeric.
measurement_cols = [
    "latitude",
    "longitude",
    "z",
    "sea_water_temperature"
]

motemarine[measurement_cols] = motemarine[
    measurement_cols
].apply(
    pd.to_numeric,
    errors="coerce"
)

### Mote Marine Missing Values

The missing QC unit is metadata and cannot be reliably inferred, so it is left
missing.

Environmental measurement values are not median-imputed because there is not
enough justification to replace an unrecorded observation with a typical value.

In [798]:
print("Remaining missing values:")
print(
    motemarine.isna().sum()[
        motemarine.isna().sum() > 0
    ]
)

Remaining missing values:
latitude                        1
longitude                       1
z                               1
sea_water_temperature           1
sea_water_temperature_qc_agg    1
dtype: int64

### Mote Marine Outlier Detection

IQR is used to screen the bottom-water temperature measurement.

Latitude and longitude are not treated as generic outliers because an extreme
coordinate may simply represent a legitimate sampling location.

In [799]:
# Use bottom-water temperature as the environmental measurement for
# outlier screening.
values = motemarine["sea_water_temperature"].dropna()

Q1 = values.quantile(0.25)
Q3 = values.quantile(0.75)

IQR = Q3 - Q1

lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

print(f"Q1: {Q1:.3f}")
print(f"Q3: {Q3:.3f}")
print(f"IQR: {IQR:.3f}")
print(f"Lower bound: {lower_bound:.3f}")
print(f"Upper bound: {upper_bound:.3f}")

temperature_outliers = motemarine[
    (motemarine["sea_water_temperature"] < lower_bound) |
    (motemarine["sea_water_temperature"] > upper_bound)
]

print("Number of IQR outliers:", len(temperature_outliers))

display(temperature_outliers.head(20))

Q1: 20.630
Q3: 29.439
IQR: 8.809
Lower bound: 7.416
Upper bound: 42.653
Number of IQR outliers: 0

Empty DataFrame
Columns: [time, latitude, longitude, z, sea_water_temperature, sea_water_temperature_qc_agg]
Index: []

NutrientsFL_2006_2025.csv

In [800]:
print("Shape:", nutrientsFL.shape)

Shape: (514087, 18)

In [801]:
nutrientsFL.head()

,DataSource,StationID,Actual_DataSource,Actual_StationID,Activity_Start_Date,Activity_Start_Time,Activity_Type,RelativeDepth,Activity_Depth,Activity_Depth_Unit,Characteristic,Result_Value,Result_Unit,Value_Qualifier,Sample_Fraction,MDL,MDL_Unit,Result_Comment
0,SARASOTA_COASTALCREEK_WQ,ALL,SARASOTA_COASTALCREEK_WQ,ALL,7/28/2006 0:00,11:53:00 AM,Sample,Surface,0.5,m,"BOD, Biochemical oxygen demand",2.16,mg/l,I,NaN,NaN,NaN,NaN
1,SARASOTA_COASTALCREEK_WQ,ALL,SARASOTA_COASTALCREEK_WQ,ALL,7/28/2006 0:00,11:53:00 AM,Sample,Surface,0.5,m,"Chlorophyll a, corrected for pheophytin",21.40,ug/l,NaN,NaN,NaN,NaN,NaN
2,SARASOTA_COASTALCREEK_WQ,ALL,SARASOTA_COASTALCREEK_WQ,ALL,7/28/2006 0:00,11:53:00 AM,Sample,Surface,0.5,m,Dissolved oxygen (DO),4.25,mg/l,NaN,NaN,NaN,NaN,NaN
3,SARASOTA_COASTALCREEK_WQ,ALL,SARASOTA_COASTALCREEK_WQ,ALL,7/28/2006 0:00,11:53:00 AM,Sample,Surface,0.5,m,Dissolved oxygen saturation,54.90,percent (%),NaN,NaN,NaN,NaN,NaN
4,SARASOTA_COASTALCREEK_WQ,ALL,SARASOTA_COASTALCREEK_WQ,ALL,7/28/2006 0:00,11:53:00 AM,Sample,Surface,0.5,m,Fecal Coliform,330.00,cfu/100ml,NaN,NaN,NaN,NaN,NaN

In [802]:
missing_values = nutrientsFL.isna().sum()

print(
    missing_values[
        missing_values > 0
    ]
)

Activity_Start_Time     82051
Activity_Type           20334
RelativeDepth           50644
Activity_Depth           1911
Activity_Depth_Unit      2106
Result_Unit             54597
Value_Qualifier        426211
Sample_Fraction        323680
MDL                    216198
MDL_Unit               241369
Result_Comment         426364
dtype: int64

In [803]:
# Calculate missing-value percentages.
null_percent = nutrientsFL.isna().mean() * 100

print(
    null_percent[
        null_percent > 0
    ].sort_values(ascending=False)
)

Result_Comment         82.936157
Value_Qualifier        82.906395
Sample_Fraction        62.962106
MDL_Unit               46.951002
MDL                    42.054749
Activity_Start_Time    15.960528
Result_Unit            10.620187
RelativeDepth           9.851251
Activity_Type           3.955362
Activity_Depth_Unit     0.409658
Activity_Depth          0.371727
dtype: float64

### NutrientsFL Missing Values

The NutrientsFL dataset contains different types of environmental measurements
and sampling metadata.

Because these variables have different meanings, missing values are handled
according to the specific field:

- Categorical metadata → `"Unknown"` when appropriate.
- Primary measurement values → left missing unless the observation is unusable.
- Detection limits → left missing because they are measurement metadata.
- Sampling dates/times → left missing because they cannot be reliably inferred.
- Sampling depth → left missing when it was not recorded.
- Measurement units → left missing when the missing value has a meaningful
  relationship to the measurement, such as dimensionless pH.

In [804]:
# Categorical fields where "Unknown" is an appropriate representation
# of an unreported value.
categorical_fill_cols = [
    "Activity_Type",
    "RelativeDepth",
    "Sample_Fraction",
    "MDL_Unit",
    "Value_Qualifier"
]

nutrientsFL[categorical_fill_cols] = nutrientsFL[
    categorical_fill_cols
].fillna("Unknown")

print("Remaining missing values:")
print(
    nutrientsFL.isna().sum()[
        nutrientsFL.isna().sum() > 0
    ]
)

Remaining missing values:
Activity_Start_Time     82051
Activity_Depth           1911
Activity_Depth_Unit      2106
Result_Unit             54597
MDL                    216198
Result_Comment         426364
dtype: int64

### NutrientsFL Outlier Detection

`Result_Value` contains many different environmental measurements. Applying one
IQR calculation to the entire column would be inappropriate because the values
have different units and distributions.

Instead, IQR is calculated separately for each `Characteristic`.

In [805]:
# Get all unique characteristics that have numerical Result_Value data.
characteristics = nutrientsFL[
    "Characteristic"
].dropna().unique()

print("Number of characteristics:", len(characteristics))
print(characteristics)

Number of characteristics: 21
['BOD, Biochemical oxygen demand'
 'Chlorophyll a, corrected for pheophytin' 'Dissolved oxygen (DO)'
 'Dissolved oxygen saturation' 'Fecal Coliform' 'Nitrogen'
 'Nitrogen, ammonia as N' 'Nitrogen, Kjeldahl'
 'Nitrogen, Nitrite (NO2) + Nitrate (NO3) as N' 'pH' 'Phosphorus as P'
 'Phosphorus, phosphate (PO4) as P' 'Specific conductance'
 'Temperature, water' 'Total Suspended Solids (TSS)' 'Turbidity'
 'True Color' 'Chlorophyll a, uncorrected for pheophytin'
 'Temperature, Water' 'Dissolved Oxygen Saturation' 'Specific Conductance']

In [806]:
# Apply IQR outlier detection separately to each characteristic.
#
# Result_Value contains measurements with different units and distributions,
# so one overall IQR calculation would not be appropriate. Instead, each
# characteristic gets its own Q1, Q3, IQR, and outlier boundaries.

for characteristic in characteristics:

    # Get the Result_Value measurements for this characteristic.
    values = nutrientsFL.loc[
        nutrientsFL["Characteristic"] == characteristic,
        "Result_Value"
    ].dropna()

    # Skip characteristics that do not have numerical measurements.
    if len(values) == 0:
        continue

    # Calculate the first and third quartiles.
    Q1 = values.quantile(0.25)
    Q3 = values.quantile(0.75)

    # Calculate the interquartile range.
    IQR = Q3 - Q1

    # Calculate the IQR outlier boundaries.
    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR

    # Identify measurements outside the IQR boundaries.
    outliers = nutrientsFL.loc[
        (nutrientsFL["Characteristic"] == characteristic) &
        (
            (nutrientsFL["Result_Value"] < lower_bound) |
            (nutrientsFL["Result_Value"] > upper_bound)
        )
    ]

    print("\n" + "=" * 70)
    print(characteristic)
    print("=" * 70)

    print(f"Number of observations: {len(values)}")
    print(f"Q1: {Q1:.3f}")
    print(f"Q3: {Q3:.3f}")
    print(f"IQR: {IQR:.3f}")
    print(f"Lower bound: {lower_bound:.3f}")
    print(f"Upper bound: {upper_bound:.3f}")
    print(f"Number of IQR outliers: {len(outliers)}")

    # Display the largest outliers for inspection.
    if len(outliers) > 0:
        display(
            outliers[
                [
                    "Activity_Start_Date",
                    "StationID",
                    "Result_Value",
                    "Result_Unit",
                    "Value_Qualifier",
                    "Result_Comment"
                ]
            ].sort_values(
                "Result_Value",
                ascending=False
            ).head(20)
        )

======================================================================
BOD, Biochemical oxygen demand
======================================================================
Number of observations: 25640
Q1: 0.810
Q3: 1.710
IQR: 0.900
Lower bound: -0.540
Upper bound: 3.060
Number of IQR outliers: 2255

,Activity_Start_Date,StationID,Result_Value,Result_Unit,Value_Qualifier,Result_Comment
143768,4/6/2009 0:00,MY-A,20.0,mg/l,I,NaN
1113,6/22/2011 0:00,ALL,20.0,mg/l,Unknown,NaN
1114,6/22/2011 0:00,ALL,20.0,mg/l,Unknown,NaN
9784,5/20/2015 0:00,ALL-3,19.6,mg/l,Unknown,NaN
9785,5/20/2015 0:00,ALL-3,19.6,mg/l,Unknown,NaN
98299,3/21/2011 0:00,GOT-D,19.6,mg/l,Unknown,NaN
98300,3/21/2011 0:00,GOT-D,19.6,mg/l,Unknown,NaN
5450,6/22/2011 0:00,ALL-2,17.3,mg/l,Unknown,NaN
5451,6/22/2011 0:00,ALL-2,17.3,mg/l,Unknown,NaN
32987,5/11/2020 14:14,C341-17th,17.3,mg/l,Unknown,NaN
204481,5/20/2021 9:35,VG-1,17.2,mg/l,Unknown,NaN
197850,9/8/2014 0:00,SW-Head,17.0,mg/l,Unknown,NaN
204496,6/17/2021 9:22,VG-1,16.8,mg/l,Unknown,NaN
148024,5/18/2010 0:00,MY-B,16.7,mg/l,Unknown,NaN
33017,7/13/2020 14:17,C341-17th,16.4,mg/l,Unknown,NaN
134591,3/10/2011 0:00,MB-Fruit,16.4,mg/l,Unknown,NaN
134590,3/10/2011 0:00,MB-Fruit,16.4,mg/l,Unknown,NaN
33032,8/10/2020 14:14,C341-17th,16.1,mg/l,Unknown,NaN
138319,3/10/2011 0:00,MB-Ger,15.5,mg/l,Unknown,NaN
138320,3/10/2011 0:00,MB-Ger,15.5,mg/l,Unknown,NaN

======================================================================
Chlorophyll a, corrected for pheophytin
======================================================================
Number of observations: 26377
Q1: 2.440
Q3: 10.500
IQR: 8.060
Lower bound: -9.650
Upper bound: 22.590
Number of IQR outliers: 2556

,Activity_Start_Date,StationID,Result_Value,Result_Unit,Value_Qualifier,Result_Comment
198501,2/15/2018 0:00,SW-Head,4333.0,ug/l,Unknown,NaN
204497,6/17/2021 9:22,VG-1,2651.0,ug/l,Unknown,NaN
198541,4/17/2018 0:00,SW-Head,2403.0,ug/l,Unknown,NaN
142639,5/9/2022 9:27,ML,1573.0,ug/l,Unknown,NaN
31468,7/23/2022 12:02,BW-Tail,793.0,ug/l,Unknown,NaN
206636,6/17/2021 9:54,VG-4,674.0,ug/l,Unknown,NaN
204482,5/20/2021 9:35,VG-1,667.0,ug/l,Unknown,NaN
204633,5/23/2022 9:10,VG-1,611.0,ug/l,Unknown,NaN
206762,5/23/2022 9:26,VG-4,530.0,ug/l,Unknown,NaN
204338,7/16/2020 9:26,VG-1,518.0,ug/l,Unknown,NaN
2986,2/22/2018 0:00,ALL,517.0,ug/l,Unknown,NaN
204647,6/27/2022 9:20,VG-1,510.0,ug/l,Unknown,NaN
33018,7/13/2020 14:17,C341-17th,510.0,ug/l,Unknown,NaN
207824,6/17/2021 10:50,VG-5,507.0,ug/l,Unknown,NaN
142060,5/15/2018 0:00,ML,479.0,ug/l,Unknown,NaN
205151,5/22/2025 10:55,VG-1,467.0,ug/l,Unknown,25051153
207961,6/27/2022 10:07,VG-5,464.0,ug/l,Unknown,NaN
206775,6/27/2022 9:49,VG-4,461.0,ug/l,Unknown,NaN
206789,7/23/2022 9:30,VG-4,447.0,ug/l,Unknown,NaN
206651,7/15/2021 10:10,VG-4,444.0,ug/l,Unknown,NaN

======================================================================
Dissolved oxygen (DO)
======================================================================
Number of observations: 27143
Q1: 4.787
Q3: 7.200
IQR: 2.413
Lower bound: 1.167
Upper bound: 10.820
Number of IQR outliers: 1364

,Activity_Start_Date,StationID,Result_Value,Result_Unit,Value_Qualifier,Result_Comment
212229,1/20/2020 0:00,WH-1,171.6,mg/l,Unknown,NaN
7643,1/21/2020 0:00,ALL-2,150.4,mg/l,Unknown,NaN
216533,1/20/2020 0:00,WH-2,111.6,mg/l,Unknown,NaN
154044,1/14/2020 0:00,MY-C,110.5,mg/l,Unknown,NaN
142233,1/13/2020 0:00,ML,109.7,mg/l,Unknown,NaN
206405,1/16/2020 0:00,VG-4,107.3,mg/l,Unknown,NaN
146467,1/14/2020 0:00,MY-A,96.7,mg/l,Unknown,NaN
44094,1/20/2020 0:00,CAT-2,91.6,mg/l,Unknown,NaN
225748,1/21/2020 0:00,WOD,91.0,mg/l,Unknown,NaN
107451,1/20/2020 0:00,HUD-2,89.0,mg/l,Unknown,NaN
136316,1/13/2020 0:00,MB-Fruit,84.2,mg/l,Unknown,NaN
120938,1/13/2020 0:00,LAB-Web,83.8,mg/l,Unknown,NaN
140363,1/13/2020 0:00,MB-Ger,83.1,mg/l,Unknown,NaN
103187,1/21/2020 0:00,HAT-1,82.5,mg/l,Unknown,NaN
158142,1/14/2020 0:00,MY-E,81.9,mg/l,Unknown,NaN
115917,1/14/2020 0:00,HWC,81.7,mg/l,Unknown,NaN
207588,1/16/2020 0:00,VG-5,81.3,mg/l,Unknown,NaN
132572,1/20/2020 0:00,MAT-2,78.4,mg/l,Unknown,NaN
119091,1/13/2020 0:00,LAA-Trails,78.0,mg/l,Unknown,NaN
20907,1/14/2020 0:00,BGS-B,75.8,mg/l,Unknown,NaN

======================================================================
Dissolved oxygen saturation
======================================================================
Number of observations: 45782
Q1: 70.000
Q3: 99.000
IQR: 29.000
Lower bound: 26.500
Upper bound: 142.500
Number of IQR outliers: 2735

,Activity_Start_Date,StationID,Result_Value,Result_Unit,Value_Qualifier,Result_Comment
148509,9/10/2012 0:00,MY-B,284.00000,percent (%),Unknown,NaN
148508,9/10/2012 0:00,MY-B,284.00000,percent (%),Unknown,NaN
185371,3/22/2013 0:00,RBW-H,262.40000,percent (%),Unknown,NaN
185370,3/22/2013 0:00,RBW-H,262.40000,percent (%),Unknown,NaN
185106,5/14/2012 0:00,RBW-H,252.50000,percent (%),Unknown,NaN
185105,5/14/2012 0:00,RBW-H,252.50000,percent (%),Unknown,NaN
184921,10/11/2011 0:00,RBW-H,247.50000,percent (%),Unknown,NaN
184920,10/11/2011 0:00,RBW-H,247.50000,percent (%),Unknown,NaN
30986,4/18/2019 0:00,BW-Tail,233.20000,percent (%),Unknown,NaN
163984,3/13/2013 0:00,MYA-C,228.04698,percent (%),Unknown,Water Institute Calculated
152497,3/13/2013 0:00,MY-C,228.00000,percent (%),Unknown,NaN
152498,3/13/2013 0:00,MY-C,228.00000,percent (%),Unknown,NaN
223020,3/21/2011 0:00,WOD,225.90000,percent (%),Unknown,NaN
223019,3/21/2011 0:00,WOD,225.90000,percent (%),Unknown,NaN
163983,2/21/2013 0:00,MYA-C,225.65139,percent (%),Unknown,Water Institute Calculated
152470,2/21/2013 0:00,MY-C,225.60000,percent (%),Unknown,NaN
152469,2/21/2013 0:00,MY-C,225.60000,percent (%),Unknown,NaN
156546,2/21/2013 0:00,MY-E,217.90000,percent (%),Unknown,NaN
156545,2/21/2013 0:00,MY-E,217.90000,percent (%),Unknown,NaN
164258,2/21/2013 0:00,MYA-E,217.85799,percent (%),Unknown,Water Institute Calculated

======================================================================
Fecal Coliform
======================================================================
Number of observations: 14389
Q1: 100.000
Q3: 1400.000
IQR: 1300.000
Lower bound: -1850.000
Upper bound: 3350.000
Number of IQR outliers: 1901

,Activity_Start_Date,StationID,Result_Value,Result_Unit,Value_Qualifier,Result_Comment
109861,8/29/2012 0:00,HUD-3,194000.0,cfu/100ml,B,NaN
109860,8/29/2012 0:00,HUD-3,194000.0,cfu/100ml,B,NaN
105340,6/29/2011 0:00,HUD-2,191000.0,cfu/100ml,B,NaN
105341,6/29/2011 0:00,HUD-2,191000.0,cfu/100ml,B,NaN
176119,5/12/2025 10:49,PH-SG,190000.0,cfu/100ml,B,25050535
36320,6/12/2023 11:36,C498-Lin,176000.0,cfu/100ml,B,NaN
33858,7/21/2025 14:33,C341-17th,174000.0,cfu/100ml,B,25071120
129368,11/16/2006 0:00,MAT-2,170000.0,cfu/100ml,Unknown,NaN
33873,8/11/2025 14:38,C341-17th,167000.0,cfu/100ml,B,NaN
141370,8/11/2025 12:59,MB-Ger,160000.0,cfu/100ml,B,NaN
112693,7/28/2025 13:13,HUD-3,154000.0,cfu/100ml,B,25071545
33826,5/12/2025 14:28,C341-17th,146000.0,cfu/100ml,B,25050535
137273,5/12/2025 14:06,MB-Fruit,142000.0,cfu/100ml,B,25050535
212826,7/18/2023 14:44,WH-1,141000.0,cfu/100ml,B,NaN
13614,5/12/2025 13:58,BBB-Fruit,138000.0,cfu/100ml,B,25050535
86078,8/18/2025 12:17,ELL,135000.0,cfu/100ml,B,NaN
73689,5/5/2025 12:48,CPS-3,134000.0,cfu/100ml,B,25050200
124978,7/21/2025 13:56,LBB-Fruit,133000.0,cfu/100ml,B,25071120
4074,7/16/2024 12:01,ALL,132000.0,cfu/100ml,B,NaN
92644,8/19/2025 9:32,GOT-2,127000.0,cfu/100ml,B,NaN

======================================================================
Nitrogen
======================================================================
Number of observations: 24838
Q1: 0.375
Q3: 1.150
IQR: 0.775
Lower bound: -0.787
Upper bound: 2.312
Number of IQR outliers: 915

,Activity_Start_Date,StationID,Result_Value,Result_Unit,Value_Qualifier,Result_Comment
29583,7/23/2022 11:46,BW-Mid,54.606,mg/l,Unknown,Water Institute Calculated: TKN + NOx
27375,7/23/2022 11:26,BW-Head,44.407,mg/l,Unknown,Water Institute Calculated: TKN + NOx
197857,9/8/2014 0:00,SW-Head,23.807,mg/l,Unknown,NaN
27523,7/24/2023 12:57,BW-Head,21.161,mg/l,Unknown,Water Institute Calculated: TKN + NOx
32562,10/9/2017 9:57,C341-17th,20.653,mg/l,Unknown,Water Institute Calculated: TKN + NOx
200614,7/23/2022 12:35,SW-Mid,20.506,mg/l,Unknown,Water Institute Calculated: TKN + NOx
32815,10/8/2018 0:00,C341-17th,20.278,mg/l,Unknown,Water Institute Calculated: TKN + NOx
32327,11/14/2016 12:50,C341-17th,19.212,mg/l,Unknown,Water Institute Calculated: TKN + NOx
32310,11/14/2016 0:00,C341-17th,19.212,mg/l,Unknown,Water Institute Calculated: TKN + NOx
32584,11/13/2017 10:05,C341-17th,18.938,mg/l,Unknown,Water Institute Calculated: TKN + NOx
32295,10/17/2016 12:19,C341-17th,18.446,mg/l,Unknown,Water Institute Calculated: TKN + NOx
33080,11/10/2020 14:37,C341-17th,18.264,mg/l,Unknown,Water Institute Calculated: TKN + NOx
107133,1/22/2018 0:00,HUD-2,17.520,mg/l,Unknown,Water Institute Calculated: TKN + NOx
32268,9/22/2016 0:00,C341-17th,17.345,mg/l,Unknown,Water Institute Calculated: TKN + NOx
32745,6/12/2018 14:34,C341-17th,16.338,mg/l,Unknown,Water Institute Calculated: TKN + NOx
204662,7/23/2022 9:15,VG-1,16.006,mg/l,Unknown,Water Institute Calculated: TKN + NOx
33095,12/7/2020 14:46,C341-17th,14.658,mg/l,Unknown,Water Institute Calculated: TKN + NOx
204810,6/26/2023 9:31,VG-1,14.419,mg/l,Unknown,Water Institute Calculated: TKN + NOx
32512,8/16/2017 0:00,C341-17th,13.668,mg/l,Unknown,Water Institute Calculated: TKN + NOx
32136,3/8/2016 12:22,C341-17th,13.576,mg/l,Unknown,Water Institute Calculated: TKN + NOx

======================================================================
Nitrogen, ammonia as N
======================================================================
Number of observations: 14732
Q1: 0.015
Q3: 0.125
IQR: 0.110
Lower bound: -0.150
Upper bound: 0.290
Number of IQR outliers: 1300

,Activity_Start_Date,StationID,Result_Value,Result_Unit,Value_Qualifier,Result_Comment
32311,11/14/2016 0:00,C341-17th,16.80,mg/l,Unknown,NaN
32282,10/17/2016 0:00,C341-17th,16.50,mg/l,Unknown,NaN
32573,11/13/2017 0:00,C341-17th,13.70,mg/l,Unknown,NaN
33081,11/10/2020 14:37,C341-17th,13.60,mg/l,Unknown,NaN
33096,12/7/2020 14:46,C341-17th,13.10,mg/l,Unknown,NaN
32623,1/15/2018 0:00,C341-17th,12.00,mg/l,Unknown,NaN
32513,8/16/2017 0:00,C341-17th,11.10,mg/l,Unknown,NaN
33797,3/10/2025 13:52,C341-17th,9.77,mg/l,Unknown,NaN
32832,11/12/2018 0:00,C341-17th,8.78,mg/l,Unknown,NaN
33051,9/8/2020 14:25,C341-17th,8.46,mg/l,Unknown,NaN
32753,7/9/2018 0:00,C341-17th,7.88,mg/l,Unknown,NaN
33111,1/11/2021 14:43,C341-17th,7.77,mg/l,Unknown,NaN
32991,5/11/2020 14:14,C341-17th,7.48,mg/l,Unknown,NaN
33021,7/13/2020 14:17,C341-17th,7.24,mg/l,Unknown,NaN
33036,8/10/2020 14:14,C341-17th,7.21,mg/l,Unknown,NaN
32740,6/12/2018 0:00,C341-17th,7.14,mg/l,Unknown,NaN
33429,12/12/2022 14:42,C341-17th,6.74,mg/l,Unknown,NaN
33750,9/9/2024 14:44,C341-17th,6.50,mg/l,Unknown,NaN
33239,9/13/2021 14:45,C341-17th,6.11,mg/l,Unknown,NaN
33127,2/8/2021 14:10,C341-17th,6.00,mg/l,Unknown,NaN

======================================================================
Nitrogen, Kjeldahl
======================================================================
Number of observations: 27479
Q1: 0.390
Q3: 1.090
IQR: 0.700
Lower bound: -0.660
Upper bound: 2.140
Number of IQR outliers: 1090

,Activity_Start_Date,StationID,Result_Value,Result_Unit,Value_Qualifier,Result_Comment
29585,7/23/2022 11:46,BW-Mid,54.6,mg/l,Unknown,NaN
27377,7/23/2022 11:26,BW-Head,44.4,mg/l,Unknown,NaN
197860,9/8/2014 0:00,SW-Head,23.8,mg/l,Unknown,NaN
27525,7/24/2023 12:57,BW-Head,21.1,mg/l,Unknown,NaN
32557,10/9/2017 0:00,C341-17th,20.6,mg/l,Unknown,NaN
200616,7/23/2022 12:35,SW-Mid,20.5,mg/l,Unknown,NaN
32312,11/14/2016 0:00,C341-17th,18.9,mg/l,Unknown,NaN
32585,11/13/2017 10:05,C341-17th,18.9,mg/l,Unknown,NaN
32329,11/14/2016 12:50,C341-17th,18.9,mg/l,,NaN
32328,11/14/2016 12:50,C341-17th,18.9,mg/l,,NaN
32586,11/13/2017 10:05,C341-17th,18.9,mg/l,Unknown,NaN
32297,10/17/2016 12:19,C341-17th,18.4,mg/l,Unknown,NaN
32296,10/17/2016 12:19,C341-17th,18.4,mg/l,Unknown,NaN
33082,11/10/2020 14:37,C341-17th,17.9,mg/l,Unknown,NaN
204664,7/23/2022 9:15,VG-1,16.0,mg/l,Unknown,NaN
33097,12/7/2020 14:46,C341-17th,14.5,mg/l,Unknown,NaN
204812,6/26/2023 9:31,VG-1,14.4,mg/l,Unknown,NaN
107134,1/22/2018 0:00,HUD-2,13.8,mg/l,Unknown,NaN
32514,8/16/2017 0:00,C341-17th,13.5,mg/l,Unknown,NaN
32125,3/8/2016 0:00,C341-17th,12.8,mg/l,Unknown,NaN

======================================================================
Nitrogen, Nitrite (NO2) + Nitrate (NO3) as N
======================================================================
Number of observations: 26732
Q1: 0.005
Q3: 0.075
IQR: 0.070
Lower bound: -0.100
Upper bound: 0.180
Number of IQR outliers: 3472

,Activity_Start_Date,StationID,Result_Value,Result_Unit,Value_Qualifier,Result_Comment
30332,8/18/2016 13:07,BW-Tail,4.59,mg/l,Unknown,NaN
30333,8/18/2016 13:07,BW-Tail,4.59,mg/l,Unknown,NaN
33241,9/13/2021 14:45,C341-17th,3.96,mg/l,Unknown,NaN
107135,1/22/2018 0:00,HUD-2,3.72,mg/l,Unknown,NaN
33252,10/11/2021 14:28,C341-17th,3.61,mg/l,Unknown,NaN
32943,1/13/2020 13:41,C341-17th,3.12,mg/l,Unknown,NaN
61216,2/21/2018 0:00,CLO,2.90,mg/l,Unknown,NaN
187485,2/17/2016 0:00,RBW-SCG,2.53,mg/l,Unknown,NaN
167368,2/21/2017 0:00,NOR,2.38,mg/l,Unknown,NaN
189313,2/7/2007 0:00,RBW-W,1.88,mg/l,Unknown,NaN
20417,6/13/2017 9:00,BGS-B,1.84,mg/l,Unknown,NaN
20418,6/13/2017 9:00,BGS-B,1.84,mg/l,Unknown,NaN
194297,1/26/2011 0:00,SOU-2,1.81,mg/l,Unknown,NaN
194298,1/26/2011 0:00,SOU-2,1.81,mg/l,Unknown,NaN
33225,8/9/2021 14:38,C341-17th,1.70,mg/l,Unknown,NaN
31355,10/21/2021 10:42,BW-Tail,1.62,mg/l,Unknown,NaN
35995,1/11/2021 12:13,C498-Lin,1.51,mg/l,Unknown,NaN
116990,12/9/2025 13:02,HWC,1.48,mg/l,Unknown,NaN
189702,9/10/2009 0:00,RBW-W,1.46,mg/l,Unknown,NaN
96808,10/27/2015 0:00,GOT-C,1.45,mg/l,Unknown,NaN

======================================================================
pH
======================================================================
Number of observations: 54597
Q1: 7.600
Q3: 8.010
IQR: 0.410
Lower bound: 6.985
Upper bound: 8.625
Number of IQR outliers: 2793

,Activity_Start_Date,StationID,Result_Value,Result_Unit,Value_Qualifier,Result_Comment
104485,12/20/2007 0:00,HUD-2,758.00,NaN,Unknown,NaN
147637,4/24/2008 0:00,MY-B,677.00,NaN,Unknown,NaN
66837,12/18/2006 0:00,CPS-2,22.31,NaN,Unknown,NaN
142768,2/13/2023 0:00,ML,10.75,NaN,Unknown,NaN
187769,3/13/2017 0:00,RBW-SCG,10.70,NaN,Unknown,NaN
142285,4/13/2020 0:00,ML,10.05,NaN,Unknown,NaN
142270,3/9/2020 0:00,ML,9.98,NaN,Unknown,NaN
203013,12/14/2017 9:37,VEN_GAR-5,9.98,NaN,,NaN
186990,3/13/2018 9:14,RBW-MIR,9.97,NaN,,NaN
206377,7/18/2019 0:00,VG-4,9.94,NaN,Unknown,NaN
205786,7/21/2016 9:47,VG-4,9.92,NaN,,NaN
142190,4/16/2019 0:00,ML,9.90,NaN,Unknown,NaN
187050,8/13/2018 11:03,RBW-MIR,9.90,NaN,,NaN
142474,5/10/2021 0:00,ML,9.88,NaN,Unknown,NaN
205995,5/18/2017 10:37,VG-4,9.87,NaN,,NaN
186977,2/12/2018 9:25,RBW-MIR,9.86,NaN,,NaN
119074,9/10/2019 0:00,LAA-Trails,9.86,NaN,Unknown,NaN
187003,4/9/2018 9:20,RBW-MIR,9.86,NaN,,NaN
206619,5/20/2021 0:00,VG-4,9.82,NaN,Unknown,NaN
142052,4/9/2018 0:00,ML,9.82,NaN,Unknown,NaN

======================================================================
Phosphorus as P
======================================================================
Number of observations: 27367
Q1: 0.090
Q3: 0.316
IQR: 0.226
Lower bound: -0.249
Upper bound: 0.655
Number of IQR outliers: 1899

,Activity_Start_Date,StationID,Result_Value,Result_Unit,Value_Qualifier,Result_Comment
197865,9/8/2014 0:00,SW-Head,4.78,mg/l,Unknown,NaN
41580,6/25/2010 0:00,CAT-2,4.61,mg/l,Unknown,NaN
41579,6/25/2010 0:00,CAT-2,4.61,mg/l,Unknown,NaN
113998,5/21/2012 0:00,HWC,4.46,mg/l,Unknown,NaN
113997,5/21/2012 0:00,HWC,4.46,mg/l,Unknown,NaN
36402,3/11/2024 11:38,C498-Lin,4.25,mg/l,Unknown,NaN
121488,3/13/2023 12:02,LAB-Web,4.09,mg/l,Unknown,NaN
105235,2/22/2011 0:00,HUD-2,4.05,mg/l,Unknown,NaN
105236,2/22/2011 0:00,HUD-2,4.05,mg/l,Unknown,NaN
199092,3/21/2022 12:21,SW-Head,3.98,mg/l,Unknown,NaN
113670,6/28/2011 0:00,HWC,3.47,mg/l,Unknown,NaN
113669,6/28/2011 0:00,HWC,3.47,mg/l,Unknown,NaN
198985,4/21/2021 14:00,SW-Head,3.43,mg/l,Unknown,NaN
122446,3/17/2009 0:00,LBB-Fruit,3.42,mg/l,Unknown,NaN
113368,6/21/2010 0:00,HWC,3.36,mg/l,Unknown,NaN
113367,6/21/2010 0:00,HWC,3.36,mg/l,Unknown,NaN
112914,7/17/2008 0:00,HWC,3.30,mg/l,Unknown,NaN
34216,6/12/2008 0:00,C498-Lin,3.29,mg/l,Unknown,NaN
136896,5/16/2023 13:03,MB-Fruit,3.28,mg/l,Unknown,NaN
112898,6/30/2008 0:00,HWC,3.23,mg/l,Unknown,NaN

======================================================================
Phosphorus, phosphate (PO4) as P
======================================================================
Number of observations: 27309
Q1: 0.020
Q3: 0.204
IQR: 0.184
Lower bound: -0.256
Upper bound: 0.480
Number of IQR outliers: 1881

,Activity_Start_Date,StationID,Result_Value,Result_Unit,Value_Qualifier,Result_Comment
113999,5/21/2012 0:00,HWC,3.72,mg/l,Unknown,NaN
114000,5/21/2012 0:00,HWC,3.72,mg/l,Unknown,NaN
41582,6/25/2010 0:00,CAT-2,3.62,mg/l,Unknown,NaN
41581,6/25/2010 0:00,CAT-2,3.62,mg/l,Unknown,NaN
112899,6/30/2008 0:00,HWC,3.22,mg/l,Unknown,NaN
113369,6/21/2010 0:00,HWC,2.90,mg/l,Unknown,NaN
113370,6/21/2010 0:00,HWC,2.90,mg/l,Unknown,NaN
34217,6/12/2008 0:00,C498-Lin,2.89,mg/l,Unknown,NaN
36403,3/11/2024 11:38,C498-Lin,2.81,mg/l,Unknown,NaN
113671,6/28/2011 0:00,HWC,2.81,mg/l,Unknown,NaN
113672,6/28/2011 0:00,HWC,2.81,mg/l,Unknown,NaN
113059,5/4/2009 0:00,HWC,2.65,mg/l,Unknown,NaN
112915,7/17/2008 0:00,HWC,2.63,mg/l,Unknown,NaN
19063,5/21/2012 0:00,BGS-B,2.51,mg/l,Unknown,NaN
19062,5/21/2012 0:00,BGS-B,2.51,mg/l,Unknown,NaN
122447,3/17/2009 0:00,LBB-Fruit,2.48,mg/l,Unknown,NaN
116992,12/9/2025 13:02,HWC,2.43,mg/l,Unknown,NaN
112883,5/22/2008 0:00,HWC,2.43,mg/l,Unknown,NaN
199093,3/21/2022 12:21,SW-Head,2.41,mg/l,Unknown,NaN
222521,6/23/2009 0:00,WOD,2.17,mg/l,Unknown,NaN

======================================================================
Specific conductance
======================================================================
Number of observations: 48171
Q1: 1548.195
Q3: 52080.000
IQR: 50531.805
Lower bound: -74249.512
Upper bound: 127877.708
Number of IQR outliers: 0

======================================================================
Temperature, water
======================================================================
Number of observations: 43639
Q1: 70.520
Q3: 86.180
IQR: 15.660
Lower bound: 47.030
Upper bound: 109.670
Number of IQR outliers: 4987

,Activity_Start_Date,StationID,Result_Value,Result_Unit,Value_Qualifier,Result_Comment
171958,4/9/2018 9:00,PC-41,412.85480,deg F,Unknown,Water Institute Calculated
123890,4/9/2018 13:14,LBB-Fruit,412.85480,deg F,Unknown,Water Institute Calculated
179263,4/9/2018 9:37,RBS-Wilk,412.85480,deg F,Unknown,Water Institute Calculated
120772,4/9/2018 10:45,LAB-Web,372.06320,deg F,Unknown,Water Institute Calculated
73061,11/2/2021 0:00,CPS-3,348.79838,deg F,Unknown,Water Institute Calculated
12560,4/9/2018 12:42,BBB-Fruit,321.68120,deg F,Unknown,Water Institute Calculated
174978,4/9/2018 10:00,PH-SG,252.34520,deg F,Unknown,Water Institute Calculated
142059,4/9/2018 9:20,ML,245.05520,deg F,Unknown,Water Institute Calculated
75432,4/5/2018 11:02,CPS-AB,211.58600,deg F,Unknown,NaN
75420,4/5/2018 0:00,CPS-AB,211.58600,deg F,Unknown,NaN
189066,4/9/2018 13:14,RBW-V,211.58600,deg F,Unknown,NaN
173457,4/9/2018 9:37,PH-C,211.58600,deg F,Unknown,NaN
171948,4/9/2018 0:00,PC-41,211.58600,deg F,Unknown,NaN
65506,4/5/2018 0:00,CPS-1,211.58600,deg F,Unknown,NaN
69756,4/5/2018 9:15,CPS-2,211.58600,deg F,Unknown,NaN
69741,4/5/2018 0:00,CPS-2,211.58600,deg F,Unknown,NaN
208713,4/5/2018 11:59,VM-1,211.58600,deg F,Unknown,NaN
208702,4/5/2018 0:00,VM-1,211.58600,deg F,Unknown,NaN
73951,4/5/2018 0:00,CPS-4,211.58600,deg F,Unknown,NaN
73965,4/5/2018 10:44,CPS-4,211.58600,deg F,Unknown,NaN

======================================================================
Total Suspended Solids (TSS)
======================================================================
Number of observations: 18793
Q1: 2.900
Q3: 10.000
IQR: 7.100
Lower bound: -7.750
Upper bound: 20.650
Number of IQR outliers: 1483

,Activity_Start_Date,StationID,Result_Value,Result_Unit,Value_Qualifier,Result_Comment
197870,9/8/2014 0:00,SW-Head,2268.0,mg/l,Unknown,NaN
33786,2/10/2025 13:51,C341-17th,352.0,mg/l,Unknown,NaN
198811,3/19/2020 14:40,SW-Head,347.0,mg/l,Unknown,NaN
33026,7/13/2020 14:17,C341-17th,282.0,mg/l,Unknown,NaN
197848,7/22/2014 0:00,SW-Head,281.0,mg/l,Unknown,NaN
198830,5/21/2020 13:57,SW-Head,275.0,mg/l,Unknown,NaN
32531,8/16/2017 12:46,C341-17th,270.0,mg/l,Unknown,NaN
32530,8/16/2017 12:46,C341-17th,270.0,mg/l,Unknown,NaN
142691,8/15/2022 9:22,ML,264.0,mg/l,Unknown,NaN
206643,6/17/2021 9:54,VG-4,240.0,mg/l,Unknown,NaN
187018,5/15/2018 9:28,RBW-MIR,240.0,mg/l,,NaN
142068,5/15/2018 0:00,ML,240.0,mg/l,Unknown,NaN
143187,4/14/2025 9:37,ML,240.0,mg/l,Unknown,25040761
204504,6/17/2021 9:22,VG-1,240.0,mg/l,Unknown,NaN
228093,6/20/2012 0:00,WOD-2,227.0,mg/l,Unknown,NaN
228092,6/20/2012 0:00,WOD-2,227.0,mg/l,Unknown,NaN
142646,5/9/2022 9:27,ML,220.0,mg/l,Unknown,NaN
8740,11/15/2006 0:00,ALL-3,204.0,mg/l,Unknown,NaN
206000,5/18/2017 10:37,VG-4,200.0,mg/l,,NaN
198797,2/24/2020 13:16,SW-Head,198.0,mg/l,Unknown,NaN

======================================================================
Turbidity
======================================================================
Number of observations: 20811
Q1: 2.100
Q3: 4.600
IQR: 2.500
Lower bound: -1.650
Upper bound: 8.350
Number of IQR outliers: 1148

,Activity_Start_Date,StationID,Result_Value,Result_Unit,Value_Qualifier,Result_Comment
228095,6/20/2012 0:00,WOD-2,140.0,NTU,Unknown,NaN
228094,6/20/2012 0:00,WOD-2,140.0,NTU,Unknown,NaN
58670,2/26/2009 0:00,CLO,117.0,NTU,Unknown,NaN
205939,3/16/2017 0:00,VG-4,100.0,NTU,Unknown,NaN
60242,6/26/2014 0:00,CLO,90.0,NTU,Unknown,NaN
197849,7/22/2014 0:00,SW-Head,85.0,NTU,Unknown,NaN
228756,10/15/2014 0:00,WOD-2,80.0,NTU,Unknown,NaN
177554,2/12/2010 0:00,RBS-Wilk,76.0,NTU,Unknown,NaN
58654,1/28/2009 0:00,CLO,76.0,NTU,Unknown,NaN
98670,6/20/2012 0:00,GOT-D,75.0,NTU,Unknown,NaN
98669,6/20/2012 0:00,GOT-D,75.0,NTU,Unknown,NaN
205916,2/9/2017 0:00,VG-4,70.0,NTU,Unknown,NaN
207156,5/18/2017 0:00,VG-5,70.0,NTU,Unknown,NaN
59956,5/23/2013 0:00,CLO,70.0,NTU,Unknown,NaN
206026,7/20/2017 0:00,VG-4,70.0,NTU,Unknown,NaN
59955,5/23/2013 0:00,CLO,70.0,NTU,Unknown,NaN
98328,3/21/2011 0:00,GOT-D,66.0,NTU,Unknown,NaN
98327,3/21/2011 0:00,GOT-D,66.0,NTU,Unknown,NaN
4639,3/18/2008 0:00,ALL-2,64.4,NTU,Unknown,NaN
205302,5/22/2014 0:00,VG-4,63.0,NTU,Unknown,NaN

======================================================================
True Color
======================================================================
Number of observations: 5951
Q1: 6.000
Q3: 90.000
IQR: 84.000
Lower bound: -120.000
Upper bound: 216.000
Number of IQR outliers: 166

,Activity_Start_Date,StationID,Result_Value,Result_Unit,Value_Qualifier,Result_Comment
199003,7/15/2021 12:19,SW-Head,1000.0,PCU,Unknown,NaN
142617,3/7/2022 9:21,ML,600.0,PCU,Unknown,NaN
142602,2/7/2022 9:09,ML,600.0,PCU,Unknown,NaN
74704,10/24/2022 13:42,CPS-4,450.0,PCU,Unknown,NaN
48959,9/20/2022 14:34,CC-2,450.0,PCU,Unknown,NaN
92106,9/20/2022 9:36,GOT-2,450.0,PCU,Unknown,NaN
81231,11/8/2022 9:51,DPS,450.0,PCU,Unknown,NaN
158460,9/14/2021 11:24,MY-E,400.0,PCU,Unknown,NaN
73217,10/24/2022 13:18,CPS-3,400.0,PCU,Unknown,NaN
154535,10/27/2022 11:08,MY-C,400.0,PCU,Unknown,NaN
142551,9/13/2021 10:02,ML,400.0,PCU,Unknown,NaN
74719,11/2/2022 13:27,CPS-4,400.0,PCU,Unknown,NaN
81030,7/26/2021 11:14,DPS,400.0,PCU,Unknown,NaN
116234,9/14/2021 13:17,HWC,400.0,PCU,Unknown,NaN
204817,6/26/2023 9:31,VG-1,400.0,PCU,Unknown,NaN
207802,4/21/2021 10:53,VG-5,400.0,PCU,Unknown,NaN
158634,10/27/2022 10:37,MY-E,400.0,PCU,Unknown,NaN
206602,3/18/2021 9:20,VG-4,400.0,PCU,Unknown,NaN
162793,10/27/2022 11:49,MY-F,400.0,PCU,Unknown,NaN
204505,6/17/2021 9:22,VG-1,400.0,PCU,Unknown,NaN

======================================================================
Chlorophyll a, uncorrected for pheophytin
======================================================================
Number of observations: 2263
Q1: 2.180
Q3: 15.300
IQR: 13.120
Lower bound: -17.500
Upper bound: 34.980
Number of IQR outliers: 277

,Activity_Start_Date,StationID,Result_Value,Result_Unit,Value_Qualifier,Result_Comment
198511,2/15/2018 12:39,SW-Head,4333.0,ug/l,,NaN
198550,4/17/2018 13:06,SW-Head,2403.0,ug/l,,NaN
2997,2/22/2018 12:01,ALL,517.0,ug/l,,NaN
187009,5/15/2018 9:28,RBW-MIR,479.0,ug/l,,NaN
141749,12/12/2016 10:03,ML,332.0,ug/l,,NaN
203606,7/21/2016 9:30,VG-1,285.0,ug/l,,NaN
202958,10/18/2018 9:15,VEN_GAR-4,281.0,ug/l,,NaN
141570,4/18/2016 9:26,ML,269.0,ug/l,,NaN
204109,8/15/2018 9:00,VG-1,266.0,ug/l,,NaN
26792,7/12/2018 11:17,BW-Head,258.0,ug/l,,NaN
186998,4/9/2018 9:20,RBW-MIR,256.0,ug/l,,NaN
141770,1/11/2017 9:13,ML,252.0,ug/l,,NaN
207503,11/15/2018 9:29,VG-5,252.0,ug/l,,NaN
206114,11/16/2017 9:20,VG-4,251.0,ug/l,,NaN
207443,8/15/2018 9:33,VG-5,250.0,ug/l,,NaN
203791,4/20/2017 9:05,VG-1,248.0,ug/l,,NaN
186960,1/15/2018 9:15,RBW-MIR,245.0,ug/l,,NaN
205862,11/17/2016 9:42,VG-4,244.0,ug/l,,NaN
186972,2/12/2018 9:25,RBW-MIR,243.0,ug/l,,NaN
7401,4/19/2018 11:57,ALL-2,234.0,ug/l,,NaN

======================================================================
Temperature, Water
======================================================================
Number of observations: 11677
Q1: 70.700
Q3: 85.820
IQR: 15.120
Lower bound: 48.020
Upper bound: 108.500
Number of IQR outliers: 0

======================================================================
Dissolved Oxygen Saturation
======================================================================
Number of observations: 11759
Q1: 88.000
Q3: 104.000
IQR: 16.000
Lower bound: 64.000
Upper bound: 128.000
Number of IQR outliers: 665

,Activity_Start_Date,StationID,Result_Value,Result_Unit,Value_Qualifier,Result_Comment
313633,1/6/2021 14:35,13-1,208.0,percent (%),Unknown,NaN
237227,8/8/2018 13:03,10-1,208.0,percent (%),Unknown,NaN
237217,8/8/2018 13:02,10-1,207.0,percent (%),Unknown,NaN
485987,7/10/2019 12:43,LB-5,202.0,percent (%),Unknown,NaN
321140,8/12/2020 14:07,13-2,184.0,percent (%),Unknown,NaN
512159,8/8/2018 12:46,US-5,179.0,percent (%),Unknown,NaN
306362,7/6/2022 13:57,11-5,179.0,percent (%),Unknown,NaN
512169,8/8/2018 12:47,US-5,178.0,percent (%),Unknown,NaN
261725,5/7/2025 14:03,10-4,174.0,percent (%),Unknown,NaN
261736,5/7/2025 14:04,10-4,172.0,percent (%),Unknown,NaN
374198,6/2/2021 12:01,14-4,168.0,percent (%),Unknown,NaN
321690,9/7/2022 14:06,13-2,166.0,percent (%),Unknown,NaN
251841,8/8/2018 13:19,10-3,166.0,percent (%),Unknown,NaN
251831,8/8/2018 13:17,10-3,165.0,percent (%),Unknown,NaN
320609,7/11/2018 13:40,13-2,165.0,percent (%),Unknown,NaN
359615,2/1/2023 12:29,14-2,165.0,percent (%),Unknown,NaN
314314,8/2/2023 13:32,13-1,164.0,percent (%),Unknown,NaN
251845,8/8/2018 13:20,10-3,163.0,percent (%),Unknown,NaN
375275,7/9/2025 11:57,14-4,161.0,percent (%),Unknown,NaN
267554,8/8/2018 10:32,10-5,161.0,percent (%),Unknown,NaN

======================================================================
Specific Conductance
======================================================================
Number of observations: 8638
Q1: 48300.000
Q3: 53500.000
IQR: 5200.000
Lower bound: 40500.000
Upper bound: 61300.000
Number of IQR outliers: 499

,Activity_Start_Date,StationID,Result_Value,Result_Unit,Value_Qualifier,Result_Comment
321424,9/1/2021 13:59,13-2,40400.0,umho,Unknown,NaN
321418,9/1/2021 13:58,13-2,40400.0,umho,Unknown,NaN
486550,9/1/2021 10:01,LB-5,40400.0,umho,Unknown,NaN
306911,8/7/2024 14:07,11-5,40400.0,umho,Unknown,NaN
486544,9/1/2021 10:00,LB-5,40400.0,umho,Unknown,NaN
443079,10/12/2022 11:38,DR-4,40400.0,umho,Unknown,NaN
436701,9/9/2020 12:14,DR-3,40400.0,umho,Unknown,NaN
404084,9/9/2020 10:26,16-3,40400.0,umho,Unknown,NaN
366716,8/11/2021 12:20,14-3,40400.0,umho,Unknown,NaN
486554,9/1/2021 10:02,LB-5,40400.0,umho,Unknown,NaN
457190,7/9/2025 11:24,LB-1,40400.0,umho,Unknown,NaN
431183,11/9/2021 13:09,DR-2,40300.0,umho,Unknown,NaN
381508,9/9/2020 11:26,14-5,40300.0,umho,Unknown,NaN
381502,9/9/2020 11:25,14-5,40300.0,umho,Unknown,NaN
419815,10/12/2022 9:46,16-5,40300.0,umho,Unknown,NaN
344226,9/1/2021 13:11,13-5,40300.0,umho,Unknown,NaN
336605,7/14/2021 12:34,13-4,40200.0,umho,Unknown,NaN
336604,7/14/2021 12:34,13-4,40200.0,umho,Unknown,NaN
360281,9/3/2025 12:47,14-2,40200.0,umho,Unknown,NaN
437755,9/4/2024 14:12,DR-3,40200.0,umho,Unknown,NaN

In [807]:
# Remove clearly erroneous pH measurements.
nutrientsFL = nutrientsFL.drop(
    nutrientsFL[
        (nutrientsFL["Characteristic"] == "pH") &
        (nutrientsFL["Result_Value"] >= 22)
    ].index
)

# Remove clearly implausible water-temperature measurements.
nutrientsFL = nutrientsFL.drop(
    nutrientsFL[
        (nutrientsFL["Characteristic"] == "Temperature, water") &
        (nutrientsFL["Result_Value"] > 110)
    ].index
)

# Remove clearly implausible dissolved oxygen measurements.
nutrientsFL = nutrientsFL.drop(
    nutrientsFL[
        (nutrientsFL["Characteristic"] == "Dissolved oxygen (DO)") &
        (nutrientsFL["Result_Value"] > 20)
    ].index
)